### ISSUE TITLE
Unable to build on windows!

### ISSUE THREAD

**Issue by xbindt** [sourcejs/sourcejs.com#1]
With normal cmdprompt
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it is installed elsewhere.  [C:\Projects\Source\Source\node_modul
es\jsdom\node_modules\contextify\build\binding.sln]

with .net sdk 2.0 commant prompt:
        c:\users\xbindt.node-gyp\0.10.20\deps\uv\include\uv-private/uv-win.h(32
): fatal error C1083: Cannot open include file: 'winsock2.h': No such file or di
rectory
        Project : warning PRJ0018: The following environment variables were not
found:
    Done building target "contextify" in project "binding.sln" -- FAILED.
Done building target "Build" in project "binding.sln" -- FAILED.

Done building project "binding.sln" -- FAILED.

Build FAILED.
Project : warning PRJ0018: The following environment variables were not found:
c:\users\xbindt.node-gyp\0.10.20\deps\uv\include\uv-private/uv-win.h(32): fatal
 error C1083: Cannot open include file: 'winsock2.h': No such file or directory
    1 Warning(s)
    1 Error(s)

**Comment by xbindt** [comment]
use https://github.com/mihaifm/jsdom_binaries for a quick fix.
here you can find builded jsdom binaries for Windows (tested on Win7 x64 and Win XP)

**Comment by robhrt7** [comment]
There's more information about Windows dependencies for jsdom module here https://github.com/tmpvar/jsdom#contextify

**Comment by xbindt** [comment]
Could you add this info to youre "Basic Engine Documentation" ?

**Comment by robhrt7** [comment]
Yeah, we'll add some notes and info about common errors.

**Comment by schleumer** [comment]
I know it's a little bit late, but i had the same problem and i've "solved" it. You just need to run `npm install --msvs_version=2013` through the custom command prompt _(not so custom, it just provide some environment variables)_ "Developer Command Prompt", it's located somewhere in `C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\Tools\VsDevCmd.bat`. In my case it's provided by the Visual Studio 2013.

**Comment by robhrt7** [comment]
@schleumer Thanks for insights, this will definitely help our Windows users.

I will duplicate your solution to main repo topic https://github.com/sourcejs/Source/issues/23
